### PR TITLE
Show coordinates and clear

### PR DESCRIPTION
**Pull request by bjarnef**
- Added configuration to show coordinates
- Added configuration to allow clear (via button and right-click).

It seems to model only on updated on click and not on drag (but updated afterward when dragging map a bit).
So it you click on map to place marker, drag marker to another place and click "Save & Publish" it actually save the first location (last updated location) and not the location where you dragged the marker to :)

https://user-images.githubusercontent.com/2919859/140329447-9c9f0cf4-da11-493b-98e7-dd873ee8d636.mp4

### CODE REVIEW

**Comment by bergmania** [comment]
Thanks..

Beware we save both the marker coordinates and the bounding box coordinates, so it is possible to show a map where the marker is not centered.

Maybe we should show all 6 coordinates

**Comment by bjarnef** [comment]
I fixed the issue with dragging marker in https://github.com/bergmania/Bergmania.OpenStreetMap/pull/13/commits/0d9a57d7ac773deeb7aeedb80c02cf8d757aa93d

Scenarios:

- Click map to place marker and drag to new location => new location of marker should be saved
- Search location using autocomplete and drag to new location => new location of marker should be saved
- Drag existing saved marker to new location => new location of marker should be saved

**Comment by bergmania** [comment]
When removing the marker using mouse right-click, the coordinates are not cleared..  :(

**Comment by bjarnef** [comment]
@bergmania it is if allow clear is enabled. Yeah, probabaly a "breaking" change, but it seem odd the not allow clear, but you still could clear marker om right click. Alternative "Allow Clear" should be true by default?

**Comment by bergmania** [comment]
I think allow clear should be true by default, then it is not breaking :)

**Pull request merged**
